[package]
name = "mpv-bindings"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Safe Rust bindings to libmpv (client API)"

[lib]
name = "mpv_bindings"
path = "src/lib.rs"

[dependencies]
libc = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
pkg-config = { workspace = true }
cc = "1.0"
